### ISSUE TITLE
Teacher Checkpoints

### ISSUE THREAD

**Issue by HeegonJin** [brucewsy/AD-KD#2]
Thanks for your contribution.

Can you provide teacher checkpoints, like you did for student checkpoints?
The teacher models trained with your script does not match the performance (quite different) reported in the manuscript somehow.

**Comment by brucewsy** [comment]
Hi, we have uploaded the teacher checkpoints to Huggingface and you can download them using:  `model = BertForSequenceClassification.from_pretrained("Brucewsy/AD-KD_bert_base_uncased_" + task_name)`

**Comment by HeegonJin** [comment]
I appreciate it. again, thank you for the nice work.
